server:
  port: 4000

# 健康监测端点暴露
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#====================================== LOG ==========================================================
logging:
  #  config: classpath:logback.xml
  config: classpath:conf/logback-${spring.profiles.active}.xml
  file:
    path: /home/kamjin/springcloud-nacos-example/logs/

#====================================== FEIGN ============================================
feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: false
    response:
      enabled: false

#====================================== RIBBON ============================================
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

#====================================== HYSTRIX ============================================
hystrix:
  threadpool:
    default:
      coreSize: 1000 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000
